name: habits_application
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
  equatable: ^2.0.7
  bloc: ^9.1.0
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  fonts:
    - family: StackSans
      fonts:
        - asset: assets/fonts/StackSansNotch-SemiBold.ttf

    - family: SanFrancisco
      fonts:
        - asset: assets/fonts/SF-Pro.ttf

# Add this if you still have issues
dependency_overrides:
  analyzer: ^6.4.1